package main

import (
	"encoding/json"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/lelanddutcher/juicemount/internal/cache/pin"
	"github.com/lelanddutcher/juicemount/internal/derivatives"
	"github.com/lelanddutcher/juicemount/internal/farm"
	"github.com/lelanddutcher/juicemount/internal/jmlog"
	"github.com/lelanddutcher/juicemount/internal/netprofile"
	"github.com/lelanddutcher/juicemount/internal/thumbcache"
	"github.com/lelanddutcher/juicemount/metadata"
	jmnfs "github.com/lelanddutcher/juicemount/nfs"
)

// QLPROXY (T1.1/F4/F5) — Quick Look proxy plane, bridge side.
//
// Two pieces live here:
//
//  1. GET /ql-preview?path=<abs> — the spacebar-plays-BRAW serving endpoint.
//     A Quick Look preview extension resolves the user-facing path of a RAW
//     clip to its kind="qlpreview" sidecar asset (short faststart H.264 MP4,
//     generated by jmfarm -ql-preview) and plays THAT, never the source.
//     Local-cache-first (hit <5ms), bounded read-through populate on miss,
//     404-fast otherwise so macOS falls back gracefully. Mirrors the proven
//     /thumb-local contract one lane over (bridge/thumbs.go).
//
//  2. F5 hot-project prewarm — on a LAN-class link (or an explicit trigger),
//     hydrate poster thumbnails + QL-preview blobs for the most recently
//     modified project into the local persistent thumb cache BEFORE the user
//     leaves the desk, so offline/spacebar work costs zero network.
//
// Everything decision-shaped below takes its dependencies injected, so the
// core is unit-testable against fakes exactly like serveThumbLocal.

// qlKind is the derivative kind served by /ql-preview and hydrated by the
// prewarm pass. Same wire string as farm.QLPreviewKind.
const qlKind = farm.QLPreviewKind

// qlMediaType is the pinned Content-Type for kind "qlpreview" — mirrors
// blobMediaTypes in internal/farm/sidecar.go, which is the single authority.
const qlMediaType = "video/mp4"

// qlReadThroughCap bounds the read-through populate of ONE preview blob.
// A capped 960px/20s veryfast encode lands around 3-8MB; anything claiming to
// be far larger is refused rather than pulled onto the local SSD.
const qlReadThroughCap = 32 << 20

// ---------------------------------------------------------------------------
// /ql-preview — the Quick Look preview endpoint
// ---------------------------------------------------------------------------

// qlDeps is the injected surface of serveQLPreview (thumbLocalDeps' sibling).
type qlDeps struct {
	mount     string                                          // configured user-facing mount point ("/Volumes/zpool")
	lookup    func(rel string) (inode uint64, isDir, ok bool) // RAM mirror path→inode
	cachePath func(inode uint64) (root, rel string, ok bool)  // local cached blob (root+rel: anchored serve)
	populate  func(inode uint64) (root, rel string, ok bool)  // read-through resolve+cache
	warmDir   func(relDir string)                             // async dir warm (posters), best-effort
}

// serveQLPreview answers GET /ql-preview?path=<abs>. Contract with the appex:
//   - 200 video/mp4 → playable proxy bytes; http.ServeContent provides the
//     full Range/206 contract AVPlayer needs to seek.
//   - 404 (fast)    → the appex reports failure and macOS falls back; we kick
//     an async poster warm so the thumbnail plane still improves.
func serveQLPreview(w http.ResponseWriter, r *http.Request, d qlDeps) {
	p := r.URL.Query().Get("path")
	if p == "" || !filepath.IsAbs(p) {
		http.Error(w, "path (absolute) required", http.StatusBadRequest)
		return
	}
	p = filepath.Clean(p)
	if d.mount == "" || d.lookup == nil || d.cachePath == nil ||
		(p != d.mount && !strings.HasPrefix(p, d.mount+"/")) {
		w.Header().Set("X-JM-QL", "outside-mount")
		http.NotFound(w, r)
		return
	}
	rel := strings.TrimPrefix(strings.TrimPrefix(p, d.mount), "/")
	if rel == "" || metadata.ScanFilteredPath(rel) {
		w.Header().Set("X-JM-QL", "filtered")
		http.NotFound(w, r)
		return
	}
	inode, isDir, ok := d.lookup(rel)
	if !ok || isDir {
		w.Header().Set("X-JM-QL", "unknown-path")
		http.NotFound(w, r)
		return
	}
	// ANCHORED serve, identical discipline to /thumb-local: open through the
	// split root+rel pair so no component can be swapped for a symlink after
	// the cache answered.
	serve := func(root, rel, label string) bool {
		f, err := derivatives.OpenRegularUnder(root, rel)
		if err != nil {
			return false
		}
		defer f.Close()
		fi, serr := f.Stat()
		if serr != nil {
			return false
		}
		w.Header().Set("Content-Type", qlMediaType)
		w.Header().Set("X-JM-QL", label)
		w.Header().Set("Cache-Control", "no-store")
		http.ServeContent(w, r, "", fi.ModTime(), f)
		return true
	}
	if root, rel, ok := d.cachePath(inode); ok {
		if serve(root, rel, "hit") {
			return
		}
	}
	if d.populate != nil {
		if root, rel, ok := d.populate(inode); ok {
			if serve(root, rel, "populated") {
				return
			}
		}
	}
	if d.warmDir != nil {
		d.warmDir(path.Dir(rel))
	}
	w.Header().Set("X-JM-QL", "miss")
	http.NotFound(w, r)
}

// resolveDerivBlobPath resolves an inode's READY blob row of ANY kind to its
// absolute-on-FUSE location — the generic form of resolveThumbBlobPath
// (bridge/thumbs.go), which stays untouched because the warmer depends on its
// exact shape. Same chain: Tier-B index first, then the JM-15 one-sidecar
// reconcile for a farm-derived asset not yet ingested, then the C5 freshness
// gate against the RAM mirror before any bytes are named.
func resolveDerivBlobPath(ds *derivatives.Store, mount string, inode uint64, kind string) (mountOut, blobRel string, ok bool) {
	if ds == nil || mount == "" {
		return "", "", false
	}
	if known, _ := ds.Known(inode); !known {
		if found, ferr := farm.ReconcileOneSidecar(ds, mount, inode); ferr != nil || !found {
			return "", "", false
		}
	}
	rows, err := ds.Manifest(inode)
	if err != nil {
		return "", "", false
	}
	for _, d := range rows {
		if d.Kind != kind || d.Status != "ready" || d.BlobRelPath == nil || *d.BlobRelPath == "" {
			continue
		}
		live := liveSourceFor(inode)
		if derivRowStale(d, live) {
			rejectStaleDeriv(globalThumbCache, inode, kind, d, live)
			return "", "", false
		}
		return mount, derivatives.DerivBlobRel(inode, *d.BlobRelPath), true
	}
	return "", "", false
}

// populateDerivFromFUSE reads one derivative blob from FUSE into the local
// thumb cache under (inode, kind) and returns the CACHE path to serve from.
// Size-capped and anchored-open (O_NOFOLLOW every component) — the same guard
// set populateThumbFromFUSE applies, generalized over kinds.
func populateDerivFromFUSE(tc *thumbcache.Cache, ds *derivatives.Store, mount string, inode uint64, kind string, capBytes int64) (root, rel string, ok bool) {
	if tc == nil {
		return "", "", false
	}
	fmount, blobRel, ok := resolveDerivBlobPath(ds, mount, inode, kind)
	if !ok {
		return "", "", false
	}
	f, err := derivatives.OpenRegularUnder(fmount, blobRel)
	if err != nil {
		return "", "", false
	}
	defer f.Close()
	fi, err := f.Stat()
	if err != nil || fi.Size() <= 0 || fi.Size() > capBytes {
		return "", "", false
	}
	if _, err := tc.Put(inode, kind, f); err != nil {
		return "", "", false
	}
	return tc.PathParts(inode, kind)
}

// handleQLPreviewHTTP wires serveQLPreview to the live bridge globals.
func handleQLPreviewHTTP(w http.ResponseWriter, r *http.Request) {
	globalMu.Lock()
	rc := globalRC
	tc := globalThumbCache
	ds := globalDerivStore
	warmer := globalThumbWarmer
	mount := globalWantMountPoint
	fuseMount := globalFUSEPath
	if fuseMount == "" {
		fuseMount = globalMountPath
	}
	globalMu.Unlock()
	if rc == nil || tc == nil {
		http.Error(w, "not ready", http.StatusServiceUnavailable)
		return
	}
	serveQLPreview(w, r, qlDeps{
		mount: mount,
		lookup: func(rel string) (uint64, bool, bool) {
			e := rc.Store().LookupByPath(rel)
			if e == nil {
				return 0, false, false
			}
			return e.Inode, e.IsDir, true
		},
		cachePath: func(ino uint64) (string, string, bool) {
			// C5 freshness gate on cache hits, exactly like freshThumbCachePath:
			// the persistent cache is read BEFORE any manifest lookup, so a
			// stale preview would otherwise be served straight off local disk.
			croot, crel, ok := freshThumbCacheKindPath(ds, tc, ino, qlKind)
			return croot, crel, ok
		},
		populate: func(ino uint64) (string, string, bool) {
			return populateDerivFromFUSE(tc, ds, fuseMount, ino, qlKind, qlReadThroughCap)
		},
		warmDir: func(relDir string) {
			if warmer != nil {
				warmer.WarmDirAsync(relDir)
			}
		},
	})
}

// freshThumbCacheKindPath is freshThumbCachePath (bridge/thumbs.go)
// generalized over kinds: cache-hit lookup + C5 staleness rejection for any
// derivative kind held in the thumb cache.
func freshThumbCacheKindPath(ds *derivatives.Store, tc *thumbcache.Cache, inode uint64, kind string) (root, rel string, ok bool) {
	if tc == nil {
		return "", "", false
	}
	croot, crel, ok := tc.PathParts(inode, kind)
	if !ok {
		return "", "", false
	}
	if ds == nil {
		return croot, crel, true
	}
	rows, err := ds.Manifest(inode)
	if err != nil {
		return croot, crel, true // index unreadable — no basis to reject; serve.
	}
	for _, d := range rows {
		if d.Kind != kind || d.Status != "ready" {
			continue
		}
		live := liveSourceFor(inode)
		if derivRowStale(d, live) {
			rejectStaleDeriv(tc, inode, kind, d, live)
			return "", "", false
		}
		break
	}
	return croot, crel, true
}

// ---------------------------------------------------------------------------
// F5 — hot-project prewarm
// ---------------------------------------------------------------------------

// Tuning. The pass is background work: budgets keep it off the interactive
// lane, the cooldown keeps it off the metered bill, and the whole thing dies
// instantly when offline.
const (
	qlPrewarmPollInterval = 60 * time.Second // LAN-class poll cadence
	qlPrewarmCooldown     = 30 * time.Minute // min gap between AUTO passes
	qlPrewarmFileBudget   = 200              // newest files hydrated per pass
	qlPrewarmScanBudget   = 250_000          // max mirror entries walked per pass
	qlThumbBlobCap        = 2 << 20          // poster size cap (matches thumbWarmBlobCap)
	qlPrewarmConcurrency  = 2                // parallel hydration workers
)

// qlMediaExts gates which mirrored files count as preview-worthy. Extension
// check only — the derivative manifest is the real arbiter later.
var qlMediaExts = map[string]bool{
	".mov": true, ".mp4": true, ".m4v": true, ".mxf": true, ".mkv": true,
	".avi": true, ".mts": true, ".m2ts": true, ".braw": true, ".r3d": true,
	".wav": true, ".aif": true, ".aiff": true, ".flac": true, ".mp3": true, ".m4a": true,
}

// qlPrewarmStats is the observable state of the prewarm engine (GET /prewarm).
type qlPrewarmStats struct {
	Busy             bool   `json:"busy"`
	LastRunUnix      int64  `json:"last_run_unix"`
	LastTrigger      string `json:"last_trigger"` // "" | "lan" | "manual"
	LastDir          string `json:"last_dir"`
	FilesConsidered  int    `json:"files_considered"`
	ThumbsHydrated   int    `json:"thumbs_hydrated"`
	PreviewsHydrated int    `json:"previews_hydrated"`
	Errors           int    `json:"errors"`
	Note             string `json:"note,omitempty"`
}

var qlPrewarm struct {
	mu      sync.Mutex
	stats   qlPrewarmStats
	started bool
}

func qlStatsSnapshot() qlPrewarmStats {
	qlPrewarm.mu.Lock()
	defer qlPrewarm.mu.Unlock()
	return qlPrewarm.stats
}

func qlStatsSet(fn func(s *qlPrewarmStats)) {
	qlPrewarm.mu.Lock()
	defer qlPrewarm.mu.Unlock()
	fn(&qlPrewarm.stats)
}

// startQLPrewarm launches the LAN-class watcher once per process. Called from
// NFSServerStart (marked // QLPROXY there); safe across Stop/Start cycles —
// the loop re-reads the globals every tick, so a torn-down session simply
// no-ops until the next Start republishes them. JM_QL_PREWARM=0 disables the
// poller (the manual /prewarm trigger keeps working).
func startQLPrewarm() {
	qlPrewarm.mu.Lock()
	already := qlPrewarm.started
	qlPrewarm.started = true
	qlPrewarm.mu.Unlock()
	if already {
		return
	}
	if os.Getenv("JM_QL_PREWARM") == "0" {
		jmlog.Info("ql prewarm: LAN watcher disabled (JM_QL_PREWARM=0)")
		return
	}
	go qlPrewarmLoop()
	jmlog.Info("ql prewarm: LAN watcher armed",
		"poll", qlPrewarmPollInterval.String(), "cooldown", qlPrewarmCooldown.String())
}

// qlPrewarmLoop watches the measured link class and fires an automatic pass
// when the Mac is on a FAST link (netprofile ClassFast: >~200 MB/s — 10GbE/
// LAN). This is deliberately the MEASURED signal, not an env knob and not an
// interface-name heuristic: it can only say "fast" after real traffic proved
// the link fast, which is exactly the "before leaving the desk" condition F5
// wants. A cooldown bounds repeat passes while a long session holds the class.
func qlPrewarmLoop() {
	t := time.NewTicker(qlPrewarmPollInterval)
	defer t.Stop()
	for range t.C {
		globalMu.Lock()
		alive := globalRC != nil && globalStore != nil && globalThumbCache != nil
		globalMu.Unlock()
		if !alive || pin.IsOffline() {
			continue
		}
		st := qlStatsSnapshot()
		if st.Busy {
			continue
		}
		if st.LastTrigger == "lan" && time.Since(time.Unix(st.LastRunUnix, 0)) < qlPrewarmCooldown {
			continue
		}
		if netprofile.Default().Class() != netprofile.ClassFast {
			continue
		}
		go func() {
			n := runQLPrewarmPass("", "lan")
			jmlog.Info("ql prewarm: LAN pass complete", "hydrated", n)
		}()
	}
}

// qlChild is one mirror child the prewarm core consumes (decoupled from
// metadata.Entry so tests can build tiny fake trees).
type qlChild struct {
	Inode uint64
	Path  string
	Name  string
	IsDir bool
	Mtime time.Time
	Size  int64
}

// qlTree is the injected filesystem view of the prewarm core.
type qlTree struct {
	children func(dir string) []qlChild
}

// collectMedia walks dir depth-first within the scan budget and returns the
// media files found, NEWEST first. Recursion is bounded by qlMaxWalkDepth —
// shoot folders are shallow; a pathological tree simply truncates its tail.
const qlMaxWalkDepth = 6

func (t qlTree) collectMedia(dir string) []qlChild {
	var out []qlChild
	budget := qlPrewarmScanBudget
	var walk func(d string, depth int)
	walk = func(d string, depth int) {
		if budget <= 0 || depth > qlMaxWalkDepth {
			return
		}
		for _, k := range t.children(d) {
			budget--
			if budget <= 0 {
				return
			}
			if k.IsDir {
				if strings.HasPrefix(k.Name, ".") {
					continue
				}
				walk(k.Path, depth+1)
				continue
			}
			if k.Inode == 0 || strings.HasPrefix(k.Name, "._") || strings.HasPrefix(k.Name, ".") {
				continue
			}
			if !qlMediaExts[strings.ToLower(filepath.Ext(k.Name))] {
				continue
			}
			out = append(out, k)
		}
	}
	walk(dir, 0)
	sort.Slice(out, func(i, j int) bool { return out[i].Mtime.After(out[j].Mtime) })
	return out
}

// hotProjectDir picks the volume's "hot project": the TOP-LEVEL directory whose
// subtree contains the single most recently modified entry. All reads are RAM
// mirror lookups (~µs each) — never a backend call — so even a large tree
// costs milliseconds. Falls back to the root itself when the top level holds
// loose media rather than project folders.
func (t qlTree) hotProjectDir() string {
	kids := t.children(".")
	type cand struct {
		dir      string
		newest   time.Time
		hasMedia bool
	}
	var best cand
	root := cand{dir: "."}
	for _, k := range kids {
		if !k.IsDir || strings.HasPrefix(k.Name, ".") {
			if !k.IsDir && qlMediaExts[strings.ToLower(filepath.Ext(k.Name))] && k.Mtime.After(root.newest) {
				root.newest = k.Mtime
				root.hasMedia = true
			}
			continue
		}
		files := t.collectMedia(k.Path)
		if len(files) == 0 {
			continue
		}
		if files[0].Mtime.After(best.newest) {
			best = cand{dir: k.Path, newest: files[0].Mtime, hasMedia: true}
		}
	}
	switch {
	case best.hasMedia && (!root.hasMedia || best.newest.After(root.newest)):
		return best.dir
	case root.hasMedia:
		return root.dir
	default:
		return ""
	}
}

// hydrateOne pulls one (inode, kind) blob into the local thumb cache through
// the prefetch-class bulk lane (sheds under contention — interactive wins).
func hydrateOne(tc *thumbcache.Cache, ds *derivatives.Store, fuseMount string, inode uint64, kind string, capBytes int64) (bool, error) {
	if tc.Has(inode, kind) {
		return false, nil
	}
	release, admitted := jmnfs.TryAcquireBulkRead()
	if !admitted {
		return false, nil // shed: try again next pass
	}
	defer release()
	root, _, ok := populateDerivFromFUSE(tc, ds, fuseMount, inode, kind, capBytes)
	return ok && root != "", nil
}

// runQLPrewarmPass hydrates posters + QL previews for the newest media under
// dir ("" → auto-detect the hot project). Synchronous; callers wrap in a
// goroutine. Returns the number of blobs newly hydrated.
func runQLPrewarmPass(dir string, trigger string) int {
	qlPrewarm.mu.Lock()
	if qlPrewarm.stats.Busy {
		qlPrewarm.mu.Unlock()
		return 0
	}
	qlPrewarm.stats.Busy = true
	qlPrewarm.mu.Unlock()
	defer qlStatsSet(func(s *qlPrewarmStats) { s.Busy = false })

	// Globals are re-read at run time so Stop/Start cycles can't strand us on
	// closed handles.
	globalMu.Lock()
	rc := globalRC
	tc := globalThumbCache
	ds := globalDerivStore
	fuseMount := globalFUSEPath
	if fuseMount == "" {
		fuseMount = globalMountPath
	}
	globalMu.Unlock()
	if rc == nil || tc == nil || ds == nil {
		qlStatsSet(func(s *qlPrewarmStats) { s.Note = "not ready" })
		return 0
	}
	store := rc.Store()

	tree := qlTree{children: func(d string) []qlChild {
		kids, err := store.ListChildren(d)
		if err != nil {
			return nil
		}
		out := make([]qlChild, 0, len(kids))
		for _, e := range kids {
			out = append(out, qlChild{Inode: e.Inode, Path: e.Path, Name: e.Name,
				IsDir: e.IsDir, Mtime: e.Mtime, Size: e.Size})
		}
		return out
	}}

	if dir == "" {
		dir = tree.hotProjectDir()
	}
	if dir == "" || metadata.ScanFilteredPath(dir) {
		qlStatsSet(func(s *qlPrewarmStats) { s.Note = "no hot project found" })
		return 0
	}
	files := tree.collectMedia(dir)
	if len(files) > qlPrewarmFileBudget {
		files = files[:qlPrewarmFileBudget]
	}

	qlStatsSet(func(s *qlPrewarmStats) {
		s.LastRunUnix = time.Now().Unix()
		s.LastTrigger = trigger
		s.LastDir = dir
		s.FilesConsidered = len(files)
		s.Note = ""
	})
	if pin.IsOffline() {
		qlStatsSet(func(s *qlPrewarmStats) { s.Note = "offline — pass aborted" })
		return 0
	}

	sem := make(chan struct{}, qlPrewarmConcurrency)
	var wg sync.WaitGroup
	var mu sync.Mutex
	errs := 0
	for _, f := range files {
		if pin.IsOffline() {
			break
		}
		wg.Add(1)
		go func(f qlChild) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			localErrs := 0
			if ok, herr := hydrateOne(tc, ds, fuseMount, f.Inode, "thumbnail", qlThumbBlobCap); herr != nil {
				localErrs++
			} else if ok {
				qlStatsSet(func(s *qlPrewarmStats) { s.ThumbsHydrated++ })
			}
			if ok, herr := hydrateOne(tc, ds, fuseMount, f.Inode, qlKind, qlReadThroughCap); herr != nil {
				localErrs++
			} else if ok {
				qlStatsSet(func(s *qlPrewarmStats) { s.PreviewsHydrated++ })
			}
			if localErrs > 0 {
				mu.Lock()
				errs += localErrs
				mu.Unlock()
			}
		}(f)
	}
	wg.Wait()
	qlStatsSet(func(s *qlPrewarmStats) { s.Errors += errs })
	jmlog.Info("ql prewarm: pass done",
		"trigger", trigger, "dir", dir, "files", len(files),
		"thumbs", qlStatsSnapshot().ThumbsHydrated, "previews", qlStatsSnapshot().PreviewsHydrated)
	n := qlStatsSnapshot().PreviewsHydrated + qlStatsSnapshot().ThumbsHydrated
	return n
}

// handlePrewarmHTTP serves GET /prewarm (status JSON) and accepts an explicit
// trigger — GET or POST with ?run=1, optionally ?path=<abs dir> to scope the
// pass (default: auto-detected hot project). GET-mutation matches the
// /offline?on=… / /spool-recover convention on this control plane.
func handlePrewarmHTTP(w http.ResponseWriter, r *http.Request) {
	if r.URL.Query().Get("run") == "1" {
		dir := ""
		if p := r.URL.Query().Get("path"); p != "" {
			p = filepath.Clean(p)
			globalMu.Lock()
			mount := globalWantMountPoint
			globalMu.Unlock()
			if !filepath.IsAbs(p) || mount == "" ||
				(p != mount && !strings.HasPrefix(p, mount+"/")) {
				http.Error(w, "path outside mount", http.StatusBadRequest)
				return
			}
			dir = strings.TrimPrefix(strings.TrimPrefix(p, mount), "/")
		}
		go func() { runQLPrewarmPass(dir, "manual") }()
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"started": true, "dir": dir})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(qlStatsSnapshot())
}
